### PR TITLE
Add "greater/less than or equal to" methods

### PR DESCRIPTION
**Pull request by ihmels**

### CODE REVIEW

**Review by solodkiy — APPROVED** [review]

**Comment by solodkiy** [comment]
Could you please add tests to new methods?

**Comment by ihmels** [comment]
I added some assertions to `DurationTest::testCompareTo()` as it was done in `LocalDateTest::testCompareTo`.

**Comment by BenMorel** [comment]
Thank you!

**Comment by BenMorel** [comment]
Released as [0.4.2](https://github.com/brick/date-time/releases/tag/0.4.2). Sorry for the delay!

**Pull request merged**
