### PR TITLE
Add LocalDateRange::isIntersect method

### PR DESCRIPTION
**Pull request by solodkiy**
New methods

- LocalDateRange::isIntersect() returns whether this LocalDateRange intersect with the given date range.
- LocalDateRange::getIntersection() returns intersection this LocalDateRange with the given date range, exception if ranges do not intersect

### CODE REVIEW

**Comment by BenMorel** [comment]
Hi, thanks for your PR, looks good to me!

I just don't like the naming `isIntersect()` very much, I'd prefer `intersectsWith()`, which makes the interface fluent, just like `isEqualTo()`.

**Comment by solodkiy** [comment]
ok. What about getIntersection? Should we change it to getIntersectionWith?

**Comment by BenMorel** [comment]
Makes sense, I guess. Go ahead! 👍

**Comment by solodkiy** [comment]
Done.

**Comment by BenMorel** [comment]
Thank you, released as [0.2.1](https://github.com/brick/date-time/releases/tag/0.2.1)!

**Pull request merged**
