### PR TITLE
LocalDateRange::toNativeDatePeriod

### PR DESCRIPTION
**Pull request by solodkiy**
LocalDateRange::toNativeDatePeriod

https://github.com/brick/date-time/issues/47

### CODE REVIEW

**Comment by BenMorel** [comment]
LGTM, could you please update the CHANGELOG? And in #57 and #58 as well.

**Comment by solodkiy** [comment]
@BenMorel I tried to use same emoji, but I cannot see it in macos. Maybe we should use old good plain text instead?
image

**Comment by BenMorel** [comment]
@solodkiy It's a Unicode character that I thought would be quite universal: https://unicode-table.com/en/1F872/

Feel free to replace with another arrow that works for you: https://unicode-table.com/en/sets/arrow-symbols/, or just with `->` if you still have trouble (replace the others as well for consistency).

**Comment by solodkiy** [comment]
Changed to [U+2192](https://unicode-table.com/en/2192/)

**Comment by BenMorel** [comment]
Thanks :+1:

**Pull request merged**
