### PR TITLE
Add Native prefix (LocalTime)

### PR DESCRIPTION
**Pull request by solodkiy**
LocalTime::fromNativeDateTime
LocalTime::toNativeDateTime
LocalTime::toNativeDateTimeImmutable

https://github.com/brick/date-time/issues/47

### CODE REVIEW

**Comment by solodkiy** [comment]
@BenMorel CHANGELOG added

**Comment by BenMorel** [comment]
@solodkiy Could you please fix the conflict?

**Comment by solodkiy** [comment]
@BenMorel done

**Comment by BenMorel** [comment]
Thank you, @solodkiy!

**Pull request merged**
